services:
  pythonapp:
    build: ./python/
    depends_on:
      mysql:
        condition: service_healthy
    volumes: ['./python:/code', './secrets:/secrets'] 
    ports:
      - '55555:5000'

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_USER: webapp
      MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
    ports:
      - '3307:3307' 
    secrets:
      - secret_db_pw
      - secret_db_root_pw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt
