services:
  pythonapp:
    build: ./python/
    depends_on:
      - mysql
    volumes: ['./python:/code', './secrets:/secrets'] 
    ports:
      - '80:5000'

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
    ports:
      - '3306:3306' 
    secrets:
      - secret_db_pw
      - secret_db_root_pw

secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt